modLoader="javafml"
loaderVersion="[47,)"
license="MIT"
[[mods]] #mandatory
modId="treeplacer"
version="1.2.0"
displayName="TreePlacer"
displayURL="https://github.com/OutrightWings/treeplacer_mod" #optional
logoFile="logo.png"
#credits="Thanks for this example mod goes to Java"
authors="OutrightWings"
description='''
Saplings can dynamically generate different trees, based on the biome they are grown in, declared in data files.
'''
[[dependencies.treeplacer]]
    modId="forge"
    mandatory=true
    versionRange="[47,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.treeplacer]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.20.1,1.21)"
    ordering="NONE"
    side="BOTH"
